---
# Install  SMCRoute to join channels


#iptv_analyzer_collector_install_smcroute
- name: install smcroute
  package:
    name: smcroute
    state: present
  become: true

# - name: Check that VPN IP address is active
#   assert:
#     that: ansible_wg0.ipv4.address is defined

# AND CHECK DB SETTINGS AVAILABLE!

- name: Get channels to join
  community.mysql.mysql_query:
    login_user: root
    login_host: "{{ iptv_analyzer_database_server }}"
    login_db: "{{ iptv_analyzer_collector_mysql_query_database }}"
    login_password: "{{ iptv_analyzer_database_root_password }}"
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
    query: "{{ iptv_analyzer_collector_mysql_query }}"
#  no_log: true
  delegate_to: localhost
  become: true
  register: channel_to_join_smcroute

# - debug:
#     var: channel_to_join_smcroute

- name: Copy template to device
  template:
    src: etc/smcroute.conf.j2
    dest: /etc/smcroute.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  register: template_changed
  when: channel_to_join_smcroute is defined and (channel_to_join_smcroute.rowcount[0] | int) >0
# Copy template to device

- name: Restart smcroute service
  service:
    name: smcroute
    state: restarted
  when: template_changed.changed
  become: true

- name: Start snmpd service
  service:
    name: smcroute
    state: started
  when: not template_changed.changed
  become: true
