---
# tasks file for iptv_analyzer

# Add system user for MariaDB
- name: Create daemon group for collector
  group:
    name: "{{ iptv_analyzer_collector_system_user.name }}"
    gid: "{{ iptv_analyzer_collector_system_user.gid }}"
    system: true
    state: present
  become: true


- name: Create daemon user for collector
  user:
    name: "{{ iptv_analyzer_collector_system_user.name }}"
    password: "{{ iptv_analyzer_collector_system_user.password }}"
    uid: "{{ iptv_analyzer_collector_system_user.uid }}"
    system: true
    group: "{{ iptv_analyzer_collector_system_user.name }}"
    comment: "{{ iptv_analyzer_collector_system_user.comment }}"
    home: "{{ iptv_analyzer_collector_system_user.home }}"
    create_home: true
  become: true


# Install packages
- name: Update repositories cache and install collector packages
  apt:
    name: "{{ iptv_analyzer_collector_install_packages }}"
    state: present
    update_cache: yes
  become: true


# Clone Git Repo
# Check if dir exists
- name: Clone repo to home dir
  git:
    repo: "{{ iptv_analyzer_git_repo }}"
    dest: "{{ iptv_analyzer_collector_system_user.home }}/iptv_analyzer"
    update: false
    force: false
  become: true

# Execute autogen.sh
- name: Run autogen.sh
  command: ./autogen.sh
  args:
    chdir: "{{ iptv_analyzer_collector_system_user.home }}/iptv_analyzer"


# Find xtables
- name: Find xtables
  command: 'whereis xtables'
  register: xtables_location
  changed_when: false

- debug:
    msg: "{{ xtables_location.stdout.split()[1] }}"

# Configure with xtables path
- name: ./configure
  command: "'./configure --with-xtlibdir={{ xtables_location.stdout.split()[1] }}''"
  args:
    chdir: "{{ iptv_analyzer_collector_system_user.home }}/iptv_analyzer"

# Make
- name: Build the default target for iptv collector
  make:
    chdir: "{{ iptv_analyzer_collector_system_user.home }}/iptv_analyzer"

# Make install (become)
- name: Run 'install' target as root
  make:
    chdir: "{{ iptv_analyzer_collector_system_user.home }}/iptv_analyzer"
    target: install
  become: yes

# iptables module (become)

# Prepare IP Tables
#
# # Make iptables persisant
# echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
# echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
# sudo apt-get -y install iptables-persistent
#
#
#
# ### ORIGINAL
# From the CLI execute the following commands:
#     sudo apt update
#     sudo apt-get upgrade
#
#     sudo apt-get install -y autoconf git gcc make
#   sudo apt-get install -y linux-headers-`uname -r`
#     sudo apt-get install -y libxtables-dev
#     sudo apt-get install -y libproc-daemon-perl libproc-pid-file-perl libconfig-file-perl libdata-compare-perl liblog-log4perl-perl libnet-snmp-perl liblog-dispatch-perl
#     sudo apt-get install -y mariadb-server mariadb-client
#
# 	git clone https://github.com/bsmeding/IPTV-Analyzer
#
# cd IPTV-Analyzer/
#
# ./autogen.sh
#
# whereis xtables
# 	xtables: /usr/lib/x86_64-linux-gnu/xtables
#
#     	./configure --with-xtlibdir=/usr/lib/x86_64-linux-gnu/xtables
#
#
#     make
#
#     sudo make install
#
#     sudo insmod iptables-module/xt_mpeg2ts.ko
#
# Prepare the iptables:
#     sudo iptables -t mangle -I PREROUTING -i eth0 -p udp -m mpeg2ts --name in_eth0
#
#     sudo iptables -t mangle -I PREROUTING -i ens33 -p udp -m mpeg2ts --name in_ens33
#
# And make them persistant:
#     sudo apt-get -y install iptables-persistent
# (just answer Yes to all questions)
