---
# tasks file for iptv_analyzer

# Add system user for MariaDB
- name: Create daemon group for collector
  group:
    name: "{{ iptv_analyzer_system_user.name }}"
    gid: "{{ iptv_analyzer_system_user.gid }}"
    system: true
    state: present
  become: true


- name: Create daemon user for collector
  user:
    name: "{{ iptv_analyzer_system_user.name }}"
    password: "{{ iptv_analyzer_system_user.password }}"
    uid: "{{ iptv_analyzer_system_user.uid }}"
    system: true
    group: "{{ iptv_analyzer_system_user.name }}"
    comment: "{{ iptv_analyzer_system_user.comment }}"
    home: "{{ iptv_analyzer_system_user.home }}"
    create_home: true
  become: true


# Install packages
- name: Update repositories cache and install collector packages
  apt:
    name: "{{ iptv_analyzer_collector_install_packages }}"
    state: present
    update_cache: yes
  become: true


# Check kernel
- name: Check kernel
  command: "{{ iptv_analyzer_collector_cmd_kerel_version }}"
  register: kernel_version
  changed_when: false

# - debug:
#     msg: "{{ kernel_version }}"
- name: "Instal linux-headers-{{ kernel_version.stdout }}"
  apt:
    name: "linux-headers-{{ kernel_version.stdout }}"
    state: present
    update_cache: yes
  become: true


# Clone Git Repo
# Check if dir exists
- name: Clone repo to repo dir
  git:
    repo: "{{ iptv_analyzer_git_repo }}"
    dest: "{{ iptv_analyzer_git_repo_destination }}"
    update: no
    force: false
  become: true


# Execute autogen.sh
- name: Run autogen.sh
  shell: './autogen.sh'
  args:
    chdir: "{{ iptv_analyzer_git_repo_destination }}"
  become: true
# Find xtables
- name: Find xtables
  command: 'whereis xtables'
  register: xtables_location
  changed_when: false

- debug:
    msg: "{{ xtables_location.stdout.split()[1] }}"

# Configure with xtables path
- name: Configuring TVprobe source with custom modules path
  shell: "./configure --with-xtlibdir={{ xtables_location.stdout.split()[1] }}"
  args:
    chdir: "{{ iptv_analyzer_git_repo_destination }}"
  register: config_collector
  become: true

# Make
- name: Build the default target for iptv collector
  make:
    chdir: "{{ iptv_analyzer_git_repo_destination }}"
  become: true

# Make install (become)
- name: Run 'install' target as root
  make:
    chdir: "{{ iptv_analyzer_git_repo_destination }}"
    target: install
  become: yes

# iptables module (become)
- name: Insmod IPtables module
  shell: 'insmod iptables-module/xt_mpeg2ts.ko'
  args:
    chdir: "{{ iptv_analyzer_git_repo_destination }}"
  register: insmod_iptables_module
  become: true
  ignore_errors: true

# Wehn error check that error is file exist, otherwise error
# - debug:
#     msg: "{{ insmod_iptables_module }}"

- name: Check if error is valid
  assert:
    that:
      - "'File exists' in insmod_iptables_module.stderr"
  when: insmod_iptables_module is defined and insmod_iptables_module.failed|bool

# Prepare IP Tables


# sudo iptables -t mangle -I PREROUTING -i eth0 -p udp -m mpeg2ts --name in_eth0
# - name: Prepare the iptables for filtering mpeg2ts streams
#   iptables:
#     table: mangle
#     chain: PREROUTING
#     in_interface: "{{ iptv_analyzer_collector_interface }}"
#     protocol: udp
#     match: "mpeg2ts --name in_{{ iptv_analyzer_collector_interface }}"
#   become: yes
# Delete: sudo iptables -t mangle -D PREROUTING 1

## Above not working wel, the match with extra paramas are compiled to string (with quotes) that iptables cannot handle
- name: Check if prerouting entry exist in IPTables
  shell: "iptables  -L -t mangle | grep 'mpeg2ts'"
  become: true
  register: check_iptables_entry

- debug:
    msg: "{{ check_iptables_entry }}"

- name: Insmod IPtables module
  shell: "iptables -t mangle -I PREROUTING -i {{ iptv_analyzer_collector_interface }} -p udp -m mpeg2ts --name in_{{ iptv_analyzer_collector_interface }}"
  register: prepare_iptables_prerouting
  become: true

- name: Make iptables persistant - add answers
  shell: |
    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
    echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
    apt-get -y install iptables-persistent
  register: prepare_iptables_prerouting
  become: true

#
# # Make iptables persisant
#
#
#
#
#
#
# ### ORIGINAL
# From the CLI execute the following commands:
#     sudo apt update
#     sudo apt-get upgrade
#
#     sudo apt-get install -y autoconf git gcc make
#   sudo apt-get install -y linux-headers-`uname -r`
#     sudo apt-get install -y libxtables-dev
#     sudo apt-get install -y libproc-daemon-perl libproc-pid-file-perl libconfig-file-perl libdata-compare-perl liblog-log4perl-perl libnet-snmp-perl liblog-dispatch-perl
#     sudo apt-get install -y mariadb-server mariadb-client
#
# 	git clone https://github.com/bsmeding/IPTV-Analyzer
#
# cd IPTV-Analyzer/
#
# ./autogen.sh
#
# whereis xtables
# 	xtables: /usr/lib/x86_64-linux-gnu/xtables
#
#     	./configure --with-xtlibdir=/usr/lib/x86_64-linux-gnu/xtables
#
#
#     make
#
#     sudo make install
#
#     sudo insmod iptables-module/xt_mpeg2ts.ko
#
# Prepare the iptables:
#
#
#     sudo iptables -t mangle -I PREROUTING -i ens33 -p udp -m mpeg2ts --name in_ens33
#
# And make them persistant:
#     sudo apt-get -y install iptables-persistent
# (just answer Yes to all questions)




## Static joints toevoegen
# [08:15] Silvio van Leeuwen
#     echo "2" > /proc/sys/net/ipv4/conf/eth0/force_igmp_version
# ​[08:15] Silvio van Leeuwen
#     Nu NPO1 en RTL4 static er in staan
# ​[08:15] Silvio van Leeuwen
#     ip addr add 239.192.100.238/32 dev eth0 autojoin
# ip addr add 239.192.100.247/32 dev eth0 autojoin
# ​[08:15] Silvio van Leeuwen
#     even kijken of hij ze ook tergelijk kan meten.
