---
# tasks file for iptv_analyzer


# Install mariadb and client
- name: Update repositories cache and install database packages
  apt:
    name: "{{ iptv_analyzer_database_install_packages }}"
    update_cache: yes
  become: true

# add user


# import schema
