---
# tasks file for iptv_analyzer



# Add system user for MariaDB
- name: Create daemon group for MariaDB
  group:
    name: "{{ iptv_analyzer_database_system_user.name }}"
    gid: "{{ iptv_analyzer_database_system_user.gid }}"
    system: true
    state: present
  become: true


- name: Create daemon user for MariaDB
  user:
    name: "{{ iptv_analyzer_database_system_user.name }}"
    uid: "{{ iptv_analyzer_database_system_user.uid }}"
    system: true
    group: "{{ iptv_analyzer_database_system_user.name }}"
    comment: "{{ iptv_analyzer_database_system_user.comment }}"
    home: "{{ iptv_analyzer_database_system_user.home }}"
    create_home: false
    shell: "{{ iptv_analyzer_database_system_user.shell }}"
  become: true


# Install mariadb and client
- name: Update repositories cache and install database packages
  apt:
    name: "{{ iptv_analyzer_database_install_packages }}"
    state: present
    update_cache: yes
  become: true



### ROOT USER SETTINGS
- name: Check if a custom root password is specified
  assert:
    that:
      - iptv_analyzer_database_root_password != None
      - iptv_analyzer_database_root_password|length >6
    fail_msg: >
      Warning!! the MariaDB root password was left empty or <6 characters. Please set a custom
      password with role variable iptv_analyzer_database_root_password to secure your database
      server!

# This command will exit non-zero when the root password was set previously
- name: Check if root password is unset
  shell: >
    mysql -u root
    -p'{{ iptv_analyzer_database_root_password }}'
    -h localhost
    -S {{ iptv_analyzer_database_mariadb_socket }}
    -e "quit"
  changed_when: false
  ignore_errors: true
  register: root_pwd_check

# Repeat runs with the same password can continue idempotently, otherwise fail.
- name: Check if the specified root password is already set
  shell: >
    mysqladmin -u root -p{{ iptv_analyzer_database_root_password }} status
  changed_when: false
  ignore_errors: true
  no_log: true
  when: root_pwd_check.rc != 0
  become: true

- name: Check for previously set unix_socket in plugin column
  command: >
    mysql -N -s -S {{ iptv_analyzer_database_mariadb_socket }} -u root -p{{ iptv_analyzer_database_root_password }} -e
    "SELECT plugin from mysql.user WHERE user = 'root'"
  register: plugin_root_result
  changed_when: plugin_root_result.stdout is search('unix_socket')
  when: root_pwd_check.rc == 0
  #become: true

- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ iptv_analyzer_database_root_password }}"
    host: localhost
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
    state: present
  when: root_pwd_check.rc != 0
  become: true

- name: Remove unix_socket plugin if previously set
  command: >
    mysql -S {{ iptv_analyzer_database_mariadb_socket }} -u root -e
    "UPDATE mysql.user SET plugin = '' WHERE user = 'root'; FLUSH PRIVILEGES;"
  when:
    - root_pwd_check.rc == 0
    - plugin_root_result.stdout is search('unix_socket')
  become: true

- name: Set MariaDB root password for 127.0.0.1, ::1, FQDN
  mysql_user:
    name: root
    password: "{{ iptv_analyzer_database_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ iptv_analyzer_database_root_password }}"
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
    - "{{ ansible_fqdn }}"
  when: root_pwd_check.rc == 0
  become: true
### END ROOT USER SETTINGS

### REMOVE ANONYMOUS USER
- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: true
    login_user: root
    login_password: "{{ iptv_analyzer_database_root_password }}"
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
    state: absent
  no_log: true

- name: Remove the test database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ iptv_analyzer_database_root_password }}"
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
    state: absent

# - name: DEBUG Delete user defined databases so init script will trigger
#   mysql_db:
#     name: "{{ iptv_analyzer_database_name }}"
#     login_user: root
#     login_password: "{{ iptv_analyzer_database_root_password }}"
#     login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
#     state: absent
#   register: db_creation

- name: Create user defined databases
  mysql_db:
    name: "{{ iptv_analyzer_database_name }}"
    login_user: root
    login_password: "{{ iptv_analyzer_database_root_password }}"
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
    state: present
  register: db_creation

# Below, the databases are initialised, but only when the database was created
# in the previous step. This ensures idempotence.
# The tasks trigger an ansible-lint warning:
#   [503] Tasks that run when changed should likely be handlers
# That's not the case here, so the linter warning is ignored.

# Clone git repo for initial database script
- name: Clone repo to temp dir
  git:
    repo: "{{ iptv_analyzer_git_repo }}"
    dest: /tmp/iptv_analyzer
    update: yes
  when: db_creation.changed and iptv_analyzer_database_init_script is defined and iptv_analyzer_database_init_script|length>2

- name: Initialise databases
  mysql_db:  # noqa 503
    name: "{{ iptv_analyzer_database_name }}"
    state: import
    target: "/tmp/iptv_analyzer/database/{{ iptv_analyzer_database_init_script|basename }}"
    login_user: root
    login_password: "{{ iptv_analyzer_database_root_password }}"
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
  when: db_creation.changed and iptv_analyzer_database_init_script is defined and iptv_analyzer_database_init_script|length>2

# - name: Delete init scripts from the server
#   file:  # noqa 503
#     name: "/tmp/{{ item.item.init_script|basename }}"
#     state: absent
#   with_items: "{{ db_creation.results }}"
#   when: item.changed and item.item.init_script is defined

### ADD USERS
- name: Add default user
  mysql_user:
    name: "{{ iptv_analyzer_database_user }}"
    password: "{{ iptv_analyzer_database_password }}"
    host: localhost
    priv: "{{ iptv_analyzer_database_name }}.*:ALL"
    append_privs: "{{ item.append_privs|default('no') }}"
    login_user: root
    login_password: "{{ iptv_analyzer_database_root_password }}"
    login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
    state: present
  no_log: true
  when: iptv_analyzer_database_user is defined and iptv_analyzer_database_user|length>6 and iptv_analyzer_database_password is defined and iptv_analyzer_database_password|length>6

# Users are created by collector tasks

# - name: Create the users for collectors
#   mysql_user:
#     name: "{{ item.db_user }}"
#     password: "{{ item.db_password }}"
#     host: "{{ item.hostname|default('localhost') }}"
#     priv: "{{ iptv_analyzer_database_name }}.*:ALL"
#     append_privs: "{{ item.append_privs|default('no') }}"
#     login_user: root
#     login_password: "{{ iptv_analyzer_database_root_password }}"
#     login_unix_socket: "{{ iptv_analyzer_database_mariadb_socket }}"
#     state: present
#   no_log: true
#   with_items: "{{ iptv_analyzer_collectors }}"
#   loop_control:
#     label: "{{ item.hostname }} - {{ item.db_user }}"

- name: Remove temporary directory
  file:
    path: /tmp/iptv_analyzer
    state: absent
### END ADD USERS
