---
# tasks file for iptv_analyzer
# - name: Check if curl is installed
#   apt:
#     name: curl
#     state: present
#     update_cache: yes
#   become: true

- name: Get node source script
  get_url:
    url: https://deb.nodesource.com/setup_12.x
    dest: /tmp/node_12_source.sh
    mode: a+x

- name: Execute node source script
  shell: ./node_12_source.sh
  args:
    chdir: /tmp
  become: true

- name: Update apt and install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true

- name: Clone repo to temp dir
  git:
    repo: "{{ iptv_analyzer_git_repo }}"
    dest: /opt/iptv_analyzer
    update: yes



- name: Install NodeJS Webfrontend
  npm:
    path: /opt/iptv_analyzer/nodejs/
