---
## TODO Move nodejs outside git repo and sync. This because log folder and config modifications!

- name: Create daemon group for collector
  group:
    name: "{{ iptv_analyzer_database_frontend_user.name }}"
    gid: "{{ iptv_analyzer_database_frontend_user.gid }}"
    system: true
    state: present
  become: true


- name: Create daemon user for collector
  user:
    name: "{{ iptv_analyzer_database_frontend_user.name }}"
    password: "{{ iptv_analyzer_database_frontend_user.password }}"
    uid: "{{ iptv_analyzer_database_frontend_user.uid }}"
    system: true
    group: "{{ iptv_analyzer_database_frontend_user.name }}"
    comment: "{{ iptv_analyzer_database_frontend_user.comment }}"
    home: "{{ iptv_analyzer_database_frontend_user.home }}"
    create_home: true
  become: true

- name: Get node source script
  get_url:
    url: https://deb.nodesource.com/setup_12.x
    dest: /tmp/node_12_source.sh
    mode: a+x

- name: Execute node source script
  shell: ./node_12_source.sh
  args:
    chdir: /tmp
  become: true
  changed_when: false

- name: Update apt and install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true


- name: Clone repo to home dir
  git:
    repo: "{{ iptv_analyzer_git_repo }}"
    dest: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer"
    update: yes
    force: true
  become: true

- name: Install NodeJS Webfrontend
  npm:
    path: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer"
  become: true

- name: Install NodeJS Webfrontend forever
  npm:
#    path: "/home/{{ iptv_analyzer_database_frontend_user.name }}/iptv_analyzer"
    name: forever
    global: yes
    state: latest
  become: true

# Logging directory
- name: Check logging directory /var/log/tvprobe
  file:
    path: /var/log/tvprobe
    state: directory
  become: true

- name: Create symbolic link for log files
  file:
    src: "/var/log/tvprobe"
    dest: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/logs"
    state: link
    force: true
  become: true

- name: Check if config file exist
  stat: "path={{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js"
  register: frontend_config_stat

- name: Copy config file sample to config
  command: "cp {{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js.sample {{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js"
  when: not frontend_config_stat.stat.exists
  become: true

## Change config

- name: Set listening port of frontend
  lineinfile:
    path: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.http_port ='
    line: "config.http_port = {{ iptv_analyzer_database_frontend_port }};"
  become: true

- name: Set username starting frontend
  lineinfile:
    path: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.linux_user ='
    line: "config.linux_user = '{{ iptv_analyzer_database_frontend_user.name }}';"
  become: true

- name: Set user group  of frontend
  lineinfile:
    path: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.linux_group ='
    line: "config.linux_group = '{{ iptv_analyzer_database_frontend_user.name }}';"
  become: true

- name: Set db username for frontend
  lineinfile:
    path: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.db_user ='
    line: "config.db_user = '{{ iptv_analyzer_database_user }}';"
  become: true

- name: Set db password for frontend
  lineinfile:
    path: "{{ iptv_analyzer_database_frontend_user.home }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.db_password ='
    line: "config.db_password = '{{ iptv_analyzer_database_password }}';"
  become: true

# Setup auto start of frontend
## As this script stays in de git repo and changes, maybe better to move out of the repo. Consideration
- name: Set execute permission to script
  file:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/scripts/tvprobe"
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Set db username for startup script
  lineinfile:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/scripts/tvprobe"
    regexp: '^DAEMON_PATH='
    line: 'DAEMON_PATH="/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/"'
  become: true

- name: Create symbolic link for startup script
  file:
    src: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/scripts/tvprobe"
    dest: "/etc/init.d/tvprobe"
    state: link
    mode: u=rwx,g=rx,o=rx
#    force: true
  become: true

- name: Update service tvprobe to autostart and start directly
  systemd:
    name: tvprobe
    enabled: yes
    state: started
  become: true

- name: Set execute permission to script for daily maintenance
  file:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/scripts/daily_maintenance.sh"
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Ensure daily maintenance job runs daily
  cron:
    name: "check dirs"
    minute: "0"
    hour: "2"
    job: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/scripts/daily_maintenance.sh > /dev/null 2>&1"
