---

- name: Create daemon group for Frontend
  group:
    name: "{{ iptv_analyzer_database_frontend_username }}"
    system: true
    state: present
  become: true

- name: Create daemon  user "{{ iptv_analyzer_database_frontend_username }}"
  user:
    name: "{{ iptv_analyzer_database_frontend_username }}"
    groups: "{{ iptv_analyzer_database_frontend_username }}"
    shell: /sbin/nologin
    append: yes
    comment: "IPTV Analyzer frontend user"
    state: present
  become: true

- name: Get node source script
  get_url:
    url: https://deb.nodesource.com/setup_12.x
    dest: /tmp/node_12_source.sh
    mode: a+x

- name: Execute node source script
  shell: ./node_12_source.sh
  args:
    chdir: /tmp
  become: true

- name: Update apt and install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true


## TODO Add user, group and clone to seperate user home dir

- name: Clone repo to temp dir
  git:
    repo: "{{ iptv_analyzer_git_repo }}"
    dest: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer"
    update: yes
  become: true

- name: Install NodeJS Webfrontend
  npm:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer"

- name: Install NodeJS Webfrontend forever
  npm:
#    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer"
    name: forever
    global: yes
    state: latest
  become: true

  
- name: Check if config file exist
  stat: "path=/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js"
  register: frontend_config_stat

- name: Copy config file sample to config
  command: "cp /home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js.sample /home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js"
  when: not frontend_config_stat.stat.exists
  become: true

## Change config

- name: Set listening port of frontend
  lineinfile:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.http_port ='
    line: "config.http_port = {{ iptv_analyzer_database_frontend_port }};"
  become: true

- name: Set username starting frontend
  lineinfile:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.linux_user ='
    line: "config.linux_user = {{ iptv_analyzer_database_frontend_username }};"
  become: true

- name: Set user group  of frontend
  lineinfile:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.linux_group ='
    line: "config.linux_group = {{ iptv_analyzer_database_frontend_username }};"
  become: true

- name: Set db username for frontend
  lineinfile:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.db_user ='
    line: "config.db_user = {{ iptv_analyzer_database_user }};"
  become: true

- name: Set db password for frontend
  lineinfile:
    path: "/home/{{ iptv_analyzer_database_frontend_username }}/iptv_analyzer/nodejs/config.js"
    regexp: '^config.db_password ='
    line: "config.db_password = {{ iptv_analyzer_database_password }};"
  become: true
