---
# tasks file for iptv_analyzer

# Install database
- name: Include database tasks
  include_tasks: database.yml
  when: iptv_analyzer_install_database|bool

# install frontend
- name: Include local database frontend tasks
  include_tasks: frontend.yml
  when: iptv_analyzer_database_install_frontend|bool


# install collector
- name: Include tasks for collector
  include_tasks: collector.yml
  when: iptv_analyzer_install_collector|bool
