---
# tasks file for iptv_analyzer

# Install database
- name: Incluse database tasks
  include_tasks: database.yml
  when: iptv_analyzer_install_database|bool

# install frontend



# install collector



# install
