---
# tasks file for iptv_analyzer

# include vars
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

# Install database
- name: Include database tasks
  include_tasks: database.yml
  when: iptv_analyzer_install_database|bool

# install frontend
- name: Include local database frontend tasks
  include_tasks: frontend.yml
  when: iptv_analyzer_database_install_frontend|bool


# install collector
- name: Include tasks for collector
  include_tasks: collector.yml
  when: iptv_analyzer_install_collector|bool

- name: Include tasks for collector snmcroute
  include_tasks: collector_smcroute.yml
  when: iptv_analyzer_collector_install_smcroute|bool
